### ISSUE TITLE
How to avoid exiting when clicking on the mask

### ISSUE THREAD

**Issue by YikaiHu** [kamranahmedse/driver.js#467]
I need a close button to close and don't want to click the overlay to close

I think should expose a config overlayClosable : boolean to control the action

**Comment by altheaFeu** [comment]
Hi @YikaiHu,

I encountered the same issue and found a solution to get around this problem.
Start by using the `allowClose: false` option in your `driverObj` configuration:
```javascript
const driverObj = driver.js.driver({
    allowClose: false,
});
```
Then create a CSS class to display the close button:
```css
.driver-popover-close-btn {
    display: flex !important;
}
```
